In [1]:
from omop_metadata_utils import DistributionCodesets, count_bar

In [3]:
table_names = {
    "tre1": "data/nottingham-tre-1.json",
    "tre2": "data/nottingham-tre-2.json"
}

codesets = DistributionCodesets(table_names)

In [5]:
codesets.plot_count_heatmap().properties(width=600, height=600)

alt.Chart(...)

In [15]:
codesets.plot_top_k_by_count(20)

alt.Chart(...)

In [20]:
codesets.tables["tre1"].head(20)

,TRE,BIOBANK,CODE,COUNT,ALTERNATIVES,DATASET,OMOP,OMOP_DESCR,CATEGORY
0,tre1,test,OMOP:313217,410,NaN,NaN,313217,Atrial fibrillation,Condition
1,tre1,test,OMOP:317576,630,NaN,NaN,317576,Coronary arteriosclerosis,Condition
2,tre1,test,OMOP:321042,260,NaN,NaN,321042,Cardiac arrest,Condition
3,tre1,test,OMOP:381316,490,NaN,NaN,381316,Cerebrovascular accident,Condition
4,tre1,test,OMOP:439777,40,NaN,NaN,439777,Anemia,Condition
5,tre1,test,OMOP:4115276,40,NaN,NaN,4115276,Non-small cell lung cancer,Condition
6,tre1,test,OMOP:4310703,40,NaN,NaN,4310703,"Non-small cell carcinoma of lung, TNM stage 1",Condition
7,tre1,test,OMOP:4329847,240,NaN,NaN,4329847,Myocardial infarction,Condition
8,tre1,test,OMOP:38003563,610,NaN,NaN,38003563,Hispanic or Latino,Ethnicity
9,tre1,test,OMOP:38003564,4770,NaN,NaN,38003564,Not Hispanic or Latino,Ethnicity
10,tre1,test,OMOP:1310034,100,NaN,NaN,1310034,3 ML amiodarone hydrochloride 50 MG/ML Prefill...,Drug
11,tre1,test,OMOP:1332419,570,NaN,NaN,1332419,amlodipine 5 MG Oral Tablet,Drug
12,tre1,test,OMOP:1378388,40,NaN,NaN,1378388,paclitaxel 100 MG Injection,Drug
13,tre1,test,OMOP:1539411,580,NaN,NaN,1539411,simvastatin 20 MG Oral Tablet,Drug
14,tre1,test,OMOP:1545959,170,NaN,NaN,1545959,atorvastatin 80 MG Oral Tablet,Drug
15,tre1,test,OMOP:19018935,410,NaN,NaN,19018935,digoxin 0.125 MG Oral Tablet,Drug
16,tre1,test,OMOP:19075601,730,NaN,NaN,19075601,clopidogrel 75 MG Oral Tablet,Drug
17,tre1,test,OMOP:19126352,640,NaN,NaN,19126352,nitroglycerin 0.4 MG/ACTUAT Mucosal Spray,Drug
18,tre1,test,OMOP:19133768,200,NaN,NaN,19133768,acetaminophen 750 MG / hydrocodone bitartrate ...,Drug
19,tre1,test,OMOP:35604087,50,NaN,NaN,35604087,cisplatin 50 MG Injection,Drug

In [21]:
codesets.tables["tre1"].head(20)

,TRE,BIOBANK,CODE,COUNT,ALTERNATIVES,DATASET,OMOP,OMOP_DESCR,CATEGORY
0,tre1,test,OMOP:313217,410,NaN,NaN,313217,Atrial fibrillation,Condition
1,tre1,test,OMOP:317576,630,NaN,NaN,317576,Coronary arteriosclerosis,Condition
2,tre1,test,OMOP:321042,260,NaN,NaN,321042,Cardiac arrest,Condition
3,tre1,test,OMOP:381316,490,NaN,NaN,381316,Cerebrovascular accident,Condition
4,tre1,test,OMOP:439777,40,NaN,NaN,439777,Anemia,Condition
5,tre1,test,OMOP:4115276,40,NaN,NaN,4115276,Non-small cell lung cancer,Condition
6,tre1,test,OMOP:4310703,40,NaN,NaN,4310703,"Non-small cell carcinoma of lung, TNM stage 1",Condition
7,tre1,test,OMOP:4329847,240,NaN,NaN,4329847,Myocardial infarction,Condition
8,tre1,test,OMOP:38003563,610,NaN,NaN,38003563,Hispanic or Latino,Ethnicity
9,tre1,test,OMOP:38003564,4770,NaN,NaN,38003564,Not Hispanic or Latino,Ethnicity
10,tre1,test,OMOP:1310034,100,NaN,NaN,1310034,3 ML amiodarone hydrochloride 50 MG/ML Prefill...,Drug
11,tre1,test,OMOP:1332419,570,NaN,NaN,1332419,amlodipine 5 MG Oral Tablet,Drug
12,tre1,test,OMOP:1378388,40,NaN,NaN,1378388,paclitaxel 100 MG Injection,Drug
13,tre1,test,OMOP:1539411,580,NaN,NaN,1539411,simvastatin 20 MG Oral Tablet,Drug
14,tre1,test,OMOP:1545959,170,NaN,NaN,1545959,atorvastatin 80 MG Oral Tablet,Drug
15,tre1,test,OMOP:19018935,410,NaN,NaN,19018935,digoxin 0.125 MG Oral Tablet,Drug
16,tre1,test,OMOP:19075601,730,NaN,NaN,19075601,clopidogrel 75 MG Oral Tablet,Drug
17,tre1,test,OMOP:19126352,640,NaN,NaN,19126352,nitroglycerin 0.4 MG/ACTUAT Mucosal Spray,Drug
18,tre1,test,OMOP:19133768,200,NaN,NaN,19133768,acetaminophen 750 MG / hydrocodone bitartrate ...,Drug
19,tre1,test,OMOP:35604087,50,NaN,NaN,35604087,cisplatin 50 MG Injection,Drug